--------------------------------------------------------
--  파일이 생성됨 - 화요일-6월-09-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CL_COMMENT_LIKES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CL_COMMENT_LIKES" 
   (	"LIKE_ID" NUMBER, 
	"COMMENT_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CL_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CL_CATEGORIES" 
   (	"CATEGORY_ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CL_CHAT_MESSAGES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CL_CHAT_MESSAGES" 
   (	"MESSAGE_ID" NUMBER, 
	"CHAT_ROOM_ID" NUMBER, 
	"SENDER_ID" NUMBER, 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CL_CHAT_ROOM_MEMBERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CL_CHAT_ROOM_MEMBERS" 
   (	"CHAT_ROOM_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"JOINED_AT" DATE DEFAULT SYSDATE, 
	"LAST_READ_MESSAGE_ID" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CL_CHAT_ROOMS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CL_CHAT_ROOMS" 
   (	"CHAT_ROOM_ID" NUMBER, 
	"ROOM_TYPE" VARCHAR2(20 BYTE), 
	"ROOM_NAME" VARCHAR2(100 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CL_COMMENTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CL_COMMENTS" 
   (	"COMMENT_ID" NUMBER, 
	"POST_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE, 
	"DELETED_AT" DATE, 
	"PARENT_COMMENT_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CL_FOLLOWS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CL_FOLLOWS" 
   (	"FOLLOW_ID" NUMBER, 
	"FOLLOWER_ID" NUMBER, 
	"FOLLOWING_ID" NUMBER, 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CL_POST_IMAGES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CL_POST_IMAGES" 
   (	"IMAGE_ID" NUMBER, 
	"POST_ID" NUMBER, 
	"IMAGE_URL" VARCHAR2(500 BYTE), 
	"ORIGINAL_NAME" VARCHAR2(255 BYTE), 
	"SAVED_NAME" VARCHAR2(255 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CL_POST_LIKES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CL_POST_LIKES" 
   (	"LIKE_ID" NUMBER, 
	"POST_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CL_POSTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CL_POSTS" 
   (	"POST_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"CATEGORY_ID" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"VIEW_COUNT" NUMBER DEFAULT 0, 
	"IS_PROMOTION" CHAR(1 BYTE) DEFAULT 'N', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE, 
	"DELETED_AT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CL_USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CL_USERS" 
   (	"USER_ID" NUMBER, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"BIO" VARCHAR2(500 BYTE), 
	"PROFILE_IMAGE_URL" VARCHAR2(500 BYTE), 
	"USER_TYPE" VARCHAR2(20 BYTE) DEFAULT 'USER', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE, 
	"SOCIAL_ID" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CL_COMMENT_LIKES
SET DEFINE OFF;
Insert into SYSTEM.CL_COMMENT_LIKES (LIKE_ID,COMMENT_ID,USER_ID,CREATED_AT) values (61,21,2,to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_COMMENT_LIKES (LIKE_ID,COMMENT_ID,USER_ID,CREATED_AT) values (71,5,2,to_date('26/06/05','RR/MM/DD'));
REM INSERTING into SYSTEM.CL_CATEGORIES
SET DEFINE OFF;
Insert into SYSTEM.CL_CATEGORIES (CATEGORY_ID,NAME,CREATED_AT) values (1,'자유게시판',to_date('26/05/28','RR/MM/DD'));
Insert into SYSTEM.CL_CATEGORIES (CATEGORY_ID,NAME,CREATED_AT) values (2,'당구장 추천',to_date('26/05/28','RR/MM/DD'));
Insert into SYSTEM.CL_CATEGORIES (CATEGORY_ID,NAME,CREATED_AT) values (3,'용품 리뷰',to_date('26/05/28','RR/MM/DD'));
Insert into SYSTEM.CL_CATEGORIES (CATEGORY_ID,NAME,CREATED_AT) values (4,'레슨 홍보',to_date('26/05/28','RR/MM/DD'));
Insert into SYSTEM.CL_CATEGORIES (CATEGORY_ID,NAME,CREATED_AT) values (5,'대회/이벤트',to_date('26/05/28','RR/MM/DD'));
Insert into SYSTEM.CL_CATEGORIES (CATEGORY_ID,NAME,CREATED_AT) values (6,'중고거래',to_date('26/05/28','RR/MM/DD'));
Insert into SYSTEM.CL_CATEGORIES (CATEGORY_ID,NAME,CREATED_AT) values (7,'업체 홍보',to_date('26/05/28','RR/MM/DD'));
REM INSERTING into SYSTEM.CL_CHAT_MESSAGES
SET DEFINE OFF;
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (9,1,2,'ㅎㅇ요',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (11,1,3,'ㅎㅇ영',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (124,29,2,'ㅎㅇ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (15,1,2,'호호',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (126,29,2,'ㅎㅇ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (19,1,3,'ㅎㅇㅎㅇ',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (128,29,2,'안녕',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (23,1,2,'안녕하시양',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (130,29,3,'응안녕',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (27,1,2,'ㅎㅎ',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (132,29,2,'ㅎㅇ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (134,29,2,'후움',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (136,29,2,'ㅎ음',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (138,29,3,'ㅋ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (37,1,3,'ㅎㅇ',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (39,1,2,'진짜하이',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (41,1,2,'ㅎㅇㅎㅇ',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (140,29,2,'엥',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (45,1,3,'ㅈㅂㅈㅂ',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (47,1,2,'ㅈㅂ',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (49,1,2,'ㅈㅂㅈㅂ',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (51,1,2,'제발~~',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (142,29,3,'시간만안뜨나',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (144,29,2,'시간뜨나',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (57,1,3,'ㅎㄹ',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (59,1,2,'웅',to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (145,29,2,'시간뜨나',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (147,29,2,'시간떠야해',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (65,1,2,'ㅎㅇ',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (67,1,3,'ㅇㅇ',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (69,1,2,'ㅇㅇ',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (71,1,2,'ㅋㅋ',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (73,1,3,'흠',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (75,1,3,'따이양',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (77,29,2,'ㅎㅇ',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (79,29,3,'넹',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (149,29,2,'ㅈㅂ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (151,29,3,'ㅋㅋ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (153,29,2,'웅',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (85,29,3,'ㅇㅇ',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (155,1,2,'아나',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (88,29,2,'ㅎㅇ용',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (157,1,3,'굿',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (91,29,2,'훔',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (159,1,2,'하이',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (94,29,2,'흠',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (161,1,3,'ㅇㅇ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (97,29,2,'안녕',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (163,1,2,'안물',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (100,29,3,'ㅋㅋ',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (165,29,2,'ㅋㅋ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (103,29,2,'호오오',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (168,29,2,'ㅇ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (106,29,2,'ㅋㅋㅋㅋㅋㅋ',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (171,29,2,'ㅋ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (109,29,2,'흠!',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (174,29,2,'ㅋㅋㅋ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (112,29,2,'앙녕',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (114,29,2,'안녕',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (116,1,2,'ㅎㅇ',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (118,29,2,'ㅎㅇ',to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (120,1,2,'안녕',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (122,29,2,'ㅎㅇㅎㅇ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (176,29,3,'ㅋㅋㅋ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (178,29,2,'ㅋㅋㅋ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (180,29,2,'ㅎㅎㅎㅎ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (182,29,3,'ㅎㅎ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (184,29,2,'앵',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (186,29,3,'뭐지',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (188,29,2,'됏겟ㅈ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (190,29,3,'ㅇㅇ',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (192,29,2,'하아',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (194,29,2,'짜증나네',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (196,29,2,'그만하자',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (198,29,3,'휴',to_date('26/06/05','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_MESSAGES (MESSAGE_ID,CHAT_ROOM_ID,SENDER_ID,CONTENT,CREATED_AT) values (200,29,2,'하하하하',to_date('26/06/05','RR/MM/DD'));
REM INSERTING into SYSTEM.CL_CHAT_ROOM_MEMBERS
SET DEFINE OFF;
Insert into SYSTEM.CL_CHAT_ROOM_MEMBERS (CHAT_ROOM_ID,USER_ID,JOINED_AT,LAST_READ_MESSAGE_ID) values (29,2,to_date('26/06/04','RR/MM/DD'),194);
Insert into SYSTEM.CL_CHAT_ROOM_MEMBERS (CHAT_ROOM_ID,USER_ID,JOINED_AT,LAST_READ_MESSAGE_ID) values (29,3,to_date('26/06/04','RR/MM/DD'),196);
REM INSERTING into SYSTEM.CL_CHAT_ROOMS
SET DEFINE OFF;
Insert into SYSTEM.CL_CHAT_ROOMS (CHAT_ROOM_ID,ROOM_TYPE,ROOM_NAME,CREATED_AT,UPDATED_AT) values (1,'GLOBAL','전체 채팅방',to_date('26/05/28','RR/MM/DD'),to_date('26/05/28','RR/MM/DD'));
Insert into SYSTEM.CL_CHAT_ROOMS (CHAT_ROOM_ID,ROOM_TYPE,ROOM_NAME,CREATED_AT,UPDATED_AT) values (29,'DIRECT',null,to_date('26/06/04','RR/MM/DD'),null);
REM INSERTING into SYSTEM.CL_COMMENTS
SET DEFINE OFF;
Insert into SYSTEM.CL_COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT,DELETED_AT,PARENT_COMMENT_ID) values (1,30,2,'맞습니다 조명우짱',to_date('26/06/02','RR/MM/DD'),null,null,null);
Insert into SYSTEM.CL_COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT,DELETED_AT,PARENT_COMMENT_ID) values (2,30,2,'후후후',to_date('26/06/02','RR/MM/DD'),null,null,null);
Insert into SYSTEM.CL_COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT,DELETED_AT,PARENT_COMMENT_ID) values (3,29,2,'///',to_date('26/06/02','RR/MM/DD'),null,null,null);
Insert into SYSTEM.CL_COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT,DELETED_AT,PARENT_COMMENT_ID) values (4,31,3,'아뇨잘몰라요',to_date('26/06/02','RR/MM/DD'),null,null,null);
Insert into SYSTEM.CL_COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT,DELETED_AT,PARENT_COMMENT_ID) values (5,32,2,'네고 가능한가요?',to_date('26/06/04','RR/MM/DD'),null,null,null);
Insert into SYSTEM.CL_COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT,DELETED_AT,PARENT_COMMENT_ID) values (21,32,2,'@jk빌리어드 ㅋㅋㅋ ',to_date('26/06/05','RR/MM/DD'),null,null,null);
Insert into SYSTEM.CL_COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT,DELETED_AT,PARENT_COMMENT_ID) values (22,32,2,'@jk빌리어드 넹',to_date('26/06/05','RR/MM/DD'),null,null,21);
Insert into SYSTEM.CL_COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT,DELETED_AT,PARENT_COMMENT_ID) values (23,32,2,'@jk빌리어드 안도ㅑㅐ요',to_date('26/06/05','RR/MM/DD'),null,null,5);
Insert into SYSTEM.CL_COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT,DELETED_AT,PARENT_COMMENT_ID) values (24,32,2,'ㅋㅋ',to_date('26/06/05','RR/MM/DD'),null,null,null);
Insert into SYSTEM.CL_COMMENTS (COMMENT_ID,POST_ID,USER_ID,CONTENT,CREATED_AT,UPDATED_AT,DELETED_AT,PARENT_COMMENT_ID) values (25,32,2,'@jk빌리어드 왜안돼요',to_date('26/06/05','RR/MM/DD'),null,null,5);
REM INSERTING into SYSTEM.CL_FOLLOWS
SET DEFINE OFF;
Insert into SYSTEM.CL_FOLLOWS (FOLLOW_ID,FOLLOWER_ID,FOLLOWING_ID,CREATED_AT) values (13,3,2,to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_FOLLOWS (FOLLOW_ID,FOLLOWER_ID,FOLLOWING_ID,CREATED_AT) values (14,2,3,to_date('26/06/04','RR/MM/DD'));
REM INSERTING into SYSTEM.CL_POST_IMAGES
SET DEFINE OFF;
Insert into SYSTEM.CL_POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,ORIGINAL_NAME,SAVED_NAME,CREATED_AT) values (1,27,'/uploads/1780304593305.jpg','ë¤ì´ë¡ë.jfif','1780296992351.jfif',to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.CL_POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,ORIGINAL_NAME,SAVED_NAME,CREATED_AT) values (2,29,'/uploads/editor/1780624342571.jpg',null,null,to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.CL_POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,ORIGINAL_NAME,SAVED_NAME,CREATED_AT) values (3,30,'/uploads/editor/1780624334497.jpg',null,null,to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.CL_POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,ORIGINAL_NAME,SAVED_NAME,CREATED_AT) values (4,31,'/uploads/editor/1780624326404.jpg',null,null,to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,ORIGINAL_NAME,SAVED_NAME,CREATED_AT) values (5,32,'/uploads/editor/1780624319055.jpg',null,null,to_date('26/06/04','RR/MM/DD'));
Insert into SYSTEM.CL_POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,ORIGINAL_NAME,SAVED_NAME,CREATED_AT) values (21,41,'/uploads/editor/1780965494663.jfif',null,null,to_date('26/06/09','RR/MM/DD'));
REM INSERTING into SYSTEM.CL_POST_LIKES
SET DEFINE OFF;
Insert into SYSTEM.CL_POST_LIKES (LIKE_ID,POST_ID,USER_ID,CREATED_AT) values (22,31,2,to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_POST_LIKES (LIKE_ID,POST_ID,USER_ID,CREATED_AT) values (19,30,2,to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_POST_LIKES (LIKE_ID,POST_ID,USER_ID,CREATED_AT) values (23,31,3,to_date('26/06/02','RR/MM/DD'));
REM INSERTING into SYSTEM.CL_POSTS
SET DEFINE OFF;
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (1,2,2,'인천에 진짜 관리 잘 된 당구장 추천합니다',129,'N',to_date('26/05/29','RR/MM/DD'),null,to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (2,2,1,'[수정]23점 치는 당린이 근황....',0,'N',to_date('26/05/29','RR/MM/DD'),to_date('26/05/29','RR/MM/DD'),to_date('26/05/29','RR/MM/DD'));
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (3,2,3,'안녕하세요',27,'N',to_date('26/06/01','RR/MM/DD'),to_date('26/06/01','RR/MM/DD'),to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (4,3,1,'ㅇ',4,'N',to_date('26/06/01','RR/MM/DD'),null,to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (5,3,3,'무사시 하이엔드',12,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (6,2,1,'안녕하세요 처음 인사드립니다 당린이입니다^^',1,'N',to_date('26/06/01','RR/MM/DD'),to_date('26/06/01','RR/MM/DD'),to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (7,21,5,'jk배 23점 이하 대회 개최합니다~',0,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (8,21,1,'배고파요 흑흑',0,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (9,21,2,'혹시 cm당구장 괜찮은가요?',0,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (10,1,1,'오늘 처음 당구 시작했습니다!',12,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (11,2,2,'인천 당구장 맛집 추천합니다',45,'Y',to_date('26/06/01','RR/MM/DD'),null,to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (12,1,1,'큐대 추천 좀 부탁드려요',9,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (13,2,1,'당구 3쿠션 잘 치는 꿀팁',102,'N',to_date('26/06/01','RR/MM/DD'),null,to_date('26/06/01','RR/MM/DD'));
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (14,1,2,'송도 근처 당구장 어디가 좋나요?',23,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (15,22,1,'당구 4구 150점 달성!',151,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (16,23,1,'3쿠션 두께 연습 방법 공유',86,'Y',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (17,24,2,'인천 당구장 추천합니다',43,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (18,25,1,'초보자 큐대 추천 좀 해주세요',63,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (19,26,1,'오늘 당구장에서 멘탈 나갔네요..',32,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (20,22,2,'부평 깔끔한 당구장 리스트',99,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (21,23,1,'뒤돌려치기 잘하는 팁',120,'Y',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (22,24,1,'당구 게임 매너에 대해서',25,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (23,25,2,'연습하기 좋은 조용한 당구장',55,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (24,26,1,'오늘 처음 시작했는데 재미있네요!',72,'N',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (27,2,1,'조명우 큐 ',1,'N',to_date('26/06/01','RR/MM/DD'),to_date('26/06/01','RR/MM/DD'),to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (28,2,3,'조명우 큐 써봤어요',0,'N',to_date('26/06/01','RR/MM/DD'),null,to_date('26/06/02','RR/MM/DD'));
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (29,2,3,'테스트',0,'N',to_date('26/06/01','RR/MM/DD'),to_date('26/06/05','RR/MM/DD'),null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (30,2,2,'조명우짱',0,'N',to_date('26/06/01','RR/MM/DD'),to_date('26/06/05','RR/MM/DD'),null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (31,2,5,'김가영 대회우승',0,'N',to_date('26/06/02','RR/MM/DD'),to_date('26/06/05','RR/MM/DD'),null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (32,2,6,'김행직 큐 판매합니다',0,'N',to_date('26/06/04','RR/MM/DD'),to_date('26/06/05','RR/MM/DD'),null);
Insert into SYSTEM.CL_POSTS (POST_ID,USER_ID,CATEGORY_ID,TITLE,VIEW_COUNT,IS_PROMOTION,CREATED_AT,UPDATED_AT,DELETED_AT) values (41,3,1,'배고픕니다...',0,'N',to_date('26/06/09','RR/MM/DD'),null,null);
REM INSERTING into SYSTEM.CL_USERS
SET DEFINE OFF;
Insert into SYSTEM.CL_USERS (USER_ID,EMAIL,PASSWORD,NICKNAME,BIO,PROFILE_IMAGE_URL,USER_TYPE,CREATED_AT,UPDATED_AT,SOCIAL_ID) values (1,'cuelink_test@example.com','$2b$10$hND/DYCEgUIHo5/KO1sBme0G/5PGsKCPO8iznOoUBcTpQ6dNF9/xi','당구마스터',null,null,'USER',to_date('26/05/28','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_USERS (USER_ID,EMAIL,PASSWORD,NICKNAME,BIO,PROFILE_IMAGE_URL,USER_TYPE,CREATED_AT,UPDATED_AT,SOCIAL_ID) values (2,'th3613@naver.com','$2b$10$Q7tNitCUA2THaQCqoK9Q4eVCUrK42RXuoW.XTKUsBr9.o9Bq8F/LC','jk빌리어드','조명우신','/uploads/editor/1780627546825.jpg','USER',to_date('26/05/28','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_USERS (USER_ID,EMAIL,PASSWORD,NICKNAME,BIO,PROFILE_IMAGE_URL,USER_TYPE,CREATED_AT,UPDATED_AT,SOCIAL_ID) values (3,'th3926@naver.com','$2b$10$aKVZMlZduxMn3PlcwQf/iOou0C.7Sm4hTrTN0QBBPpjsmTRPk.5k6','계양구1번','퀸가영','/uploads/editor/1780638498892.jpg','USER',to_date('26/05/29','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_USERS (USER_ID,EMAIL,PASSWORD,NICKNAME,BIO,PROFILE_IMAGE_URL,USER_TYPE,CREATED_AT,UPDATED_AT,SOCIAL_ID) values (22,'test1@cue.com','test1234','당구왕김철수',null,null,'USER',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_USERS (USER_ID,EMAIL,PASSWORD,NICKNAME,BIO,PROFILE_IMAGE_URL,USER_TYPE,CREATED_AT,UPDATED_AT,SOCIAL_ID) values (23,'test2@cue.com','$2b$10$S9V9G/n.Z9u.9W1eM1eMye.p3C7J4/y8P8c6W1eM1eM1eM1eM1eM1','큐대장님',null,null,'USER',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_USERS (USER_ID,EMAIL,PASSWORD,NICKNAME,BIO,PROFILE_IMAGE_URL,USER_TYPE,CREATED_AT,UPDATED_AT,SOCIAL_ID) values (24,'test3@cue.com','$2b$10$S9V9G/n.Z9u.9W1eM1eMye.p3C7J4/y8P8c6W1eM1eM1eM1eM1eM1','삼쿠션마스터',null,null,'USER',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_USERS (USER_ID,EMAIL,PASSWORD,NICKNAME,BIO,PROFILE_IMAGE_URL,USER_TYPE,CREATED_AT,UPDATED_AT,SOCIAL_ID) values (25,'test4@cue.com','$2b$10$S9V9G/n.Z9u.9W1eM1eMye.p3C7J4/y8P8c6W1eM1eM1eM1eM1eM1','길게치기달인',null,null,'USER',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_USERS (USER_ID,EMAIL,PASSWORD,NICKNAME,BIO,PROFILE_IMAGE_URL,USER_TYPE,CREATED_AT,UPDATED_AT,SOCIAL_ID) values (26,'test5@cue.com','$2b$10$S9V9G/n.Z9u.9W1eM1eMye.p3C7J4/y8P8c6W1eM1eM1eM1eM1eM1','당구입문생',null,null,'USER',to_date('26/06/01','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_USERS (USER_ID,EMAIL,PASSWORD,NICKNAME,BIO,PROFILE_IMAGE_URL,USER_TYPE,CREATED_AT,UPDATED_AT,SOCIAL_ID) values (21,'kakao_4919757534@cuelink.temp','SOCIAL_LOGIN','이태화_8723',null,null,'USER',to_date('26/05/29','RR/MM/DD'),null,null);
Insert into SYSTEM.CL_USERS (USER_ID,EMAIL,PASSWORD,NICKNAME,BIO,PROFILE_IMAGE_URL,USER_TYPE,CREATED_AT,UPDATED_AT,SOCIAL_ID) values (41,'ock965@gmail.com','SOCIAL_LOGIN','이태화_8820',null,null,'USER',to_date('26/06/05','RR/MM/DD'),null,null);
--------------------------------------------------------
--  DDL for Index SYS_C008487
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008487" ON "SYSTEM"."CL_COMMENT_LIKES" ("LIKE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_CL_COMMENT_LIKES
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UK_CL_COMMENT_LIKES" ON "SYSTEM"."CL_COMMENT_LIKES" ("COMMENT_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008425
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008425" ON "SYSTEM"."CL_CATEGORIES" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008426
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008426" ON "SYSTEM"."CL_CATEGORIES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008478
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008478" ON "SYSTEM"."CL_CHAT_MESSAGES" ("MESSAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CL_CHAT_ROOM_MEMBERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_CL_CHAT_ROOM_MEMBERS" ON "SYSTEM"."CL_CHAT_ROOM_MEMBERS" ("CHAT_ROOM_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008467
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008467" ON "SYSTEM"."CL_CHAT_ROOMS" ("CHAT_ROOM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008446
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008446" ON "SYSTEM"."CL_COMMENTS" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008460
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008460" ON "SYSTEM"."CL_FOLLOWS" ("FOLLOW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_CL_FOLLOWS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UK_CL_FOLLOWS" ON "SYSTEM"."CL_FOLLOWS" ("FOLLOWER_ID", "FOLLOWING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008440
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008440" ON "SYSTEM"."CL_POST_IMAGES" ("IMAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008452
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008452" ON "SYSTEM"."CL_POST_LIKES" ("LIKE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_CL_POST_LIKES
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UK_CL_POST_LIKES" ON "SYSTEM"."CL_POST_LIKES" ("POST_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008435
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008435" ON "SYSTEM"."CL_POSTS" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008421
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008421" ON "SYSTEM"."CL_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008422
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008422" ON "SYSTEM"."CL_USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CL_COMMENT_LIKES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_COMMENT_LIKES" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_COMMENT_LIKES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_COMMENT_LIKES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_COMMENT_LIKES" ADD PRIMARY KEY ("LIKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CL_COMMENT_LIKES" ADD CONSTRAINT "UK_CL_COMMENT_LIKES" UNIQUE ("COMMENT_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_CATEGORIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_CATEGORIES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_CATEGORIES" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CL_CATEGORIES" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_CHAT_MESSAGES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_CHAT_MESSAGES" MODIFY ("CHAT_ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_CHAT_MESSAGES" MODIFY ("SENDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_CHAT_MESSAGES" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_CHAT_MESSAGES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_CHAT_MESSAGES" ADD PRIMARY KEY ("MESSAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_CHAT_ROOM_MEMBERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_CHAT_ROOM_MEMBERS" MODIFY ("CHAT_ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_CHAT_ROOM_MEMBERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_CHAT_ROOM_MEMBERS" MODIFY ("JOINED_AT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_CHAT_ROOM_MEMBERS" ADD CONSTRAINT "PK_CL_CHAT_ROOM_MEMBERS" PRIMARY KEY ("CHAT_ROOM_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_CHAT_ROOMS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_CHAT_ROOMS" MODIFY ("ROOM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_CHAT_ROOMS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_CHAT_ROOMS" ADD CONSTRAINT "CK_CL_CHAT_ROOM_TYPE" CHECK (ROOM_TYPE IN ('GLOBAL', 'DIRECT')) ENABLE;
  ALTER TABLE "SYSTEM"."CL_CHAT_ROOMS" ADD PRIMARY KEY ("CHAT_ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_COMMENTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_COMMENTS" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_COMMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_COMMENTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_COMMENTS" ADD PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_FOLLOWS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_FOLLOWS" MODIFY ("FOLLOWER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_FOLLOWS" MODIFY ("FOLLOWING_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_FOLLOWS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_FOLLOWS" ADD CONSTRAINT "CK_CL_FOLLOWS_SELF" CHECK (FOLLOWER_ID <> FOLLOWING_ID) ENABLE;
  ALTER TABLE "SYSTEM"."CL_FOLLOWS" ADD PRIMARY KEY ("FOLLOW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CL_FOLLOWS" ADD CONSTRAINT "UK_CL_FOLLOWS" UNIQUE ("FOLLOWER_ID", "FOLLOWING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_POST_IMAGES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_POST_IMAGES" MODIFY ("IMAGE_URL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POST_IMAGES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POST_IMAGES" ADD PRIMARY KEY ("IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_POST_LIKES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_POST_LIKES" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POST_LIKES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POST_LIKES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POST_LIKES" ADD PRIMARY KEY ("LIKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CL_POST_LIKES" ADD CONSTRAINT "UK_CL_POST_LIKES" UNIQUE ("POST_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_POSTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_POSTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POSTS" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POSTS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POSTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POSTS" MODIFY ("VIEW_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POSTS" MODIFY ("IS_PROMOTION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POSTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_POSTS" ADD CONSTRAINT "CK_CL_POSTS_PROMOTION" CHECK (IS_PROMOTION IN ('Y', 'N')) ENABLE;
  ALTER TABLE "SYSTEM"."CL_POSTS" ADD PRIMARY KEY ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CL_USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_USERS" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_USERS" MODIFY ("USER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_USERS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CL_USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CL_USERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CL_USERS" ADD CONSTRAINT "CK_CL_USERS_TYPE" CHECK (USER_TYPE IN ('USER', 'ADMIN', 'GOOGLE', 'KAKAO', 'NAVER')) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_COMMENT_LIKES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_COMMENT_LIKES" ADD CONSTRAINT "FK_CL_COMMENT_LIKES_COMMENT" FOREIGN KEY ("COMMENT_ID")
	  REFERENCES "SYSTEM"."CL_COMMENTS" ("COMMENT_ID") ENABLE;
  ALTER TABLE "SYSTEM"."CL_COMMENT_LIKES" ADD CONSTRAINT "FK_CL_COMMENT_LIKES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."CL_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_CHAT_MESSAGES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_CHAT_MESSAGES" ADD CONSTRAINT "FK_CL_CHAT_MESSAGES_ROOM" FOREIGN KEY ("CHAT_ROOM_ID")
	  REFERENCES "SYSTEM"."CL_CHAT_ROOMS" ("CHAT_ROOM_ID") ENABLE;
  ALTER TABLE "SYSTEM"."CL_CHAT_MESSAGES" ADD CONSTRAINT "FK_CL_CHAT_MESSAGES_SENDER" FOREIGN KEY ("SENDER_ID")
	  REFERENCES "SYSTEM"."CL_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_CHAT_ROOM_MEMBERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_CHAT_ROOM_MEMBERS" ADD CONSTRAINT "FK_CL_CHAT_MEMBERS_ROOM" FOREIGN KEY ("CHAT_ROOM_ID")
	  REFERENCES "SYSTEM"."CL_CHAT_ROOMS" ("CHAT_ROOM_ID") ENABLE;
  ALTER TABLE "SYSTEM"."CL_CHAT_ROOM_MEMBERS" ADD CONSTRAINT "FK_CL_CHAT_MEMBERS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."CL_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_COMMENTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_COMMENTS" ADD CONSTRAINT "FK_CL_COMMENTS_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "SYSTEM"."CL_POSTS" ("POST_ID") ENABLE;
  ALTER TABLE "SYSTEM"."CL_COMMENTS" ADD CONSTRAINT "FK_CL_COMMENTS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."CL_USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."CL_COMMENTS" ADD CONSTRAINT "FK_CL_COMMENTS_PARENT" FOREIGN KEY ("PARENT_COMMENT_ID")
	  REFERENCES "SYSTEM"."CL_COMMENTS" ("COMMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_FOLLOWS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_FOLLOWS" ADD CONSTRAINT "FK_CL_FOLLOWS_FOLLOWER" FOREIGN KEY ("FOLLOWER_ID")
	  REFERENCES "SYSTEM"."CL_USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."CL_FOLLOWS" ADD CONSTRAINT "FK_CL_FOLLOWS_FOLLOWING" FOREIGN KEY ("FOLLOWING_ID")
	  REFERENCES "SYSTEM"."CL_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_POST_IMAGES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_POST_IMAGES" ADD CONSTRAINT "FK_CL_POST_IMAGES_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "SYSTEM"."CL_POSTS" ("POST_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_POST_LIKES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_POST_LIKES" ADD CONSTRAINT "FK_CL_POST_LIKES_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "SYSTEM"."CL_POSTS" ("POST_ID") ENABLE;
  ALTER TABLE "SYSTEM"."CL_POST_LIKES" ADD CONSTRAINT "FK_CL_POST_LIKES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."CL_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CL_POSTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CL_POSTS" ADD CONSTRAINT "FK_CL_POSTS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."CL_USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."CL_POSTS" ADD CONSTRAINT "FK_CL_POSTS_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "SYSTEM"."CL_CATEGORIES" ("CATEGORY_ID") ENABLE;
