-- CueLink Oracle DB Schema
-- Frontend: http://localhost:5173
-- Backend: http://localhost:4000
-- Oracle DB: localhost:1521

CREATE TABLE CL_USERS (
    USER_ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL,
    BIO VARCHAR2(500),
    PROFILE_IMAGE_URL VARCHAR2(500),
    USER_TYPE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    CONSTRAINT CK_CL_USERS_TYPE
        CHECK (USER_TYPE IN ('USER', 'BUSINESS', 'ADMIN'))
);

CREATE TABLE CL_CATEGORIES (
    CATEGORY_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL UNIQUE,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE CL_POSTS (
    POST_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    CATEGORY_ID NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,
    IS_PROMOTION CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    DELETED_AT DATE,
    CONSTRAINT FK_CL_POSTS_USER
        FOREIGN KEY (USER_ID) REFERENCES CL_USERS(USER_ID),
    CONSTRAINT FK_CL_POSTS_CATEGORY
        FOREIGN KEY (CATEGORY_ID) REFERENCES CL_CATEGORIES(CATEGORY_ID),
    CONSTRAINT CK_CL_POSTS_PROMOTION
        CHECK (IS_PROMOTION IN ('Y', 'N'))
);

CREATE TABLE CL_POST_IMAGES (
    IMAGE_ID NUMBER PRIMARY KEY,
    POST_ID NUMBER,
    IMAGE_URL VARCHAR2(500) NOT NULL,
    ORIGINAL_NAME VARCHAR2(255),
    SAVED_NAME VARCHAR2(255),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_CL_POST_IMAGES_POST
        FOREIGN KEY (POST_ID) REFERENCES CL_POSTS(POST_ID)
);

CREATE TABLE CL_COMMENTS (
    COMMENT_ID NUMBER PRIMARY KEY,
    POST_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    DELETED_AT DATE,
    CONSTRAINT FK_CL_COMMENTS_POST
        FOREIGN KEY (POST_ID) REFERENCES CL_POSTS(POST_ID),
    CONSTRAINT FK_CL_COMMENTS_USER
        FOREIGN KEY (USER_ID) REFERENCES CL_USERS(USER_ID)
);

CREATE TABLE CL_POST_LIKES (
    LIKE_ID NUMBER PRIMARY KEY,
    POST_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_CL_POST_LIKES_POST
        FOREIGN KEY (POST_ID) REFERENCES CL_POSTS(POST_ID),
    CONSTRAINT FK_CL_POST_LIKES_USER
        FOREIGN KEY (USER_ID) REFERENCES CL_USERS(USER_ID),
    CONSTRAINT UK_CL_POST_LIKES UNIQUE (POST_ID, USER_ID)
);

CREATE TABLE CL_FOLLOWS (
    FOLLOW_ID NUMBER PRIMARY KEY,
    FOLLOWER_ID NUMBER NOT NULL,
    FOLLOWING_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_CL_FOLLOWS_FOLLOWER
        FOREIGN KEY (FOLLOWER_ID) REFERENCES CL_USERS(USER_ID),
    CONSTRAINT FK_CL_FOLLOWS_FOLLOWING
        FOREIGN KEY (FOLLOWING_ID) REFERENCES CL_USERS(USER_ID),
    CONSTRAINT UK_CL_FOLLOWS UNIQUE (FOLLOWER_ID, FOLLOWING_ID),
    CONSTRAINT CK_CL_FOLLOWS_SELF
        CHECK (FOLLOWER_ID <> FOLLOWING_ID)
);

CREATE TABLE CL_CHAT_ROOMS (
    CHAT_ROOM_ID NUMBER PRIMARY KEY,
    ROOM_TYPE VARCHAR2(20) NOT NULL,
    ROOM_NAME VARCHAR2(100),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    CONSTRAINT CK_CL_CHAT_ROOM_TYPE
        CHECK (ROOM_TYPE IN ('GLOBAL', 'DIRECT'))
);

CREATE TABLE CL_CHAT_ROOM_MEMBERS (
    CHAT_ROOM_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    JOINED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CL_CHAT_ROOM_MEMBERS
        PRIMARY KEY (CHAT_ROOM_ID, USER_ID),
    CONSTRAINT FK_CL_CHAT_MEMBERS_ROOM
        FOREIGN KEY (CHAT_ROOM_ID) REFERENCES CL_CHAT_ROOMS(CHAT_ROOM_ID),
    CONSTRAINT FK_CL_CHAT_MEMBERS_USER
        FOREIGN KEY (USER_ID) REFERENCES CL_USERS(USER_ID)
);

CREATE TABLE CL_CHAT_MESSAGES (
    MESSAGE_ID NUMBER PRIMARY KEY,
    CHAT_ROOM_ID NUMBER NOT NULL,
    SENDER_ID NUMBER NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_CL_CHAT_MESSAGES_ROOM
        FOREIGN KEY (CHAT_ROOM_ID) REFERENCES CL_CHAT_ROOMS(CHAT_ROOM_ID),
    CONSTRAINT FK_CL_CHAT_MESSAGES_SENDER
        FOREIGN KEY (SENDER_ID) REFERENCES CL_USERS(USER_ID)
);

CREATE SEQUENCE SEQ_CL_USERS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CL_CATEGORIES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CL_POSTS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CL_POST_IMAGES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CL_COMMENTS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CL_POST_LIKES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CL_FOLLOWS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CL_CHAT_ROOMS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CL_CHAT_MESSAGES START WITH 1 INCREMENT BY 1 NOCACHE;

INSERT INTO CL_CATEGORIES (CATEGORY_ID, NAME)
VALUES (SEQ_CL_CATEGORIES.NEXTVAL, '자유게시판');

INSERT INTO CL_CATEGORIES (CATEGORY_ID, NAME)
VALUES (SEQ_CL_CATEGORIES.NEXTVAL, '당구장 추천');

INSERT INTO CL_CATEGORIES (CATEGORY_ID, NAME)   
VALUES (SEQ_CL_CATEGORIES.NEXTVAL, '용품 리뷰');

INSERT INTO CL_CATEGORIES (CATEGORY_ID, NAME)
VALUES (SEQ_CL_CATEGORIES.NEXTVAL, '레슨 홍보');

INSERT INTO CL_CATEGORIES (CATEGORY_ID, NAME)
VALUES (SEQ_CL_CATEGORIES.NEXTVAL, '대회/이벤트');

INSERT INTO CL_CATEGORIES (CATEGORY_ID, NAME)
VALUES (SEQ_CL_CATEGORIES.NEXTVAL, '중고거래');

INSERT INTO CL_CATEGORIES (CATEGORY_ID, NAME)
VALUES (SEQ_CL_CATEGORIES.NEXTVAL, '업체 홍보');

INSERT INTO CL_CHAT_ROOMS (CHAT_ROOM_ID, ROOM_TYPE, ROOM_NAME, UPDATED_AT)
SELECT SEQ_CL_CHAT_ROOMS.NEXTVAL, 'GLOBAL', '전체 채팅방', SYSDATE
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM CL_CHAT_ROOMS
    WHERE ROOM_TYPE = 'GLOBAL'
);

COMMIT;